version: '3'

networks:
    laravel:

services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./etc:/var/www/lagc
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
        networks:
            - laravel
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./etc:/var/www/lagc
        ports:
            - "9000:9000"
        networks: 
            - laravel